#!/usr/bin/env python

import sys, os
#sys.path[0] gives the directory of the file even if it's run 
#  from another directory, ala the muttrc files
sys.path.append(os.path.join(sys.path[0], 'lamson'))

from lamson import args, commands

args.parse_and_run_command(sys.argv[1:], commands, default_command="help")


